version: '3'

services:
  pinpeople_envoy_rabbitmq:
    container_name: pinpeople_envoy_rabbitmq
    image: rabbitmq:3.8-management
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - './.rabbitmq_data:/var/lib/rabbitmq/mnesia'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
